import { Product } from "./types";

export const products: Product[] = [
  // shirts
  {
    // shirts
    id: 1,
    title: " black shirt",
    image: ["/images/pic1.png"],
    slug: "black t shirt",
    price: 150,
    discount: 30,
    category: "Shirts",
    discrption:
      "A versatile black shirt perfect for any casual or formal occasion.",
    size: ["s", "m", "l ", "xl"],
    color: ["#fffff", "#000000", "#e60000"],
    qty: 1,
    rating: 40,
    originalPrice: 110,
  },
  {
    // shirts
    id: 1,
    title: " black shirt",
    image: ["/images/pic15.png", "/images/pic2.png"],
    slug: "black t shirt",
    price: 150,
    discount: 30,
    category: "Shirts",
    discrption:
      "A versatile black shirt perfect for any casual or formal occasion.",
    size: ["s", "m", "l ", "xl"],
    color: ["#fffff", "#000000", "#e60000"],
    qty: 1,
    rating: 40,
    originalPrice: 110,
  },
  {
    // shirts
    id: 1,
    title: " black shirt",
    image: ["/images/pic9.png", "/images/pic2.png"],
    slug: "black t shirt",
    price: 150,
    discount: 30,
    category: "Shirts",
    discrption:
      "A versatile black shirt perfect for any casual or formal occasion.",
    size: ["s", "m", "l ", "xl"],
    color: ["#fffff", "#000000", "#e60000"],
    qty: 1,
    rating: 40,
    originalPrice: 110,
  },
  {
    // shirts
    id: 1,
    title: " black shirt",
    image: ["/images/pic4.png", "/images/pic2.png"],
    slug: "black t shirt",
    price: 150,
    discount: 30,
    category: "Shirts",
    discrption:
      "A versatile black shirt perfect for any casual or formal occasion.",
    size: ["s", "m", "l ", "xl"],
    color: ["#fffff", "#000000", "#e60000"],
    qty: 1,
    rating: 40,
    originalPrice: 110,
  },
  // Tshirts
  {
    id: 2,
    title: "Tshirts",
    image: ["/images/pic1.png", "/images/pic12.png"],
    slug: "black t shirt",
    price: 150,
    discount: 50,
    category: "Tshirts",
    discrption:
      "A versatile black shirt perfect for any casual or formal occasion.",
    size: ["s", "m", "l ", "xl"],
    color: ["#fffff", "#000000", "#e60000"],
    qty: 1,
    rating: 5,
    originalPrice: 2260,
  },
  {
    id: 2,
    title: "Tshirts",
    image: ["/images/pic13.png", "/images/pic12.png"],
    slug: "black t shirt",
    price: 150,
    discount: 50,
    category: "Tshirts",
    discrption:
      "A versatile black shirt perfect for any casual or formal occasion.",
    size: ["s", "m", "l ", "xl"],
    color: ["#fffff", "#000000", "#e60000"],
    qty: 1,
    rating: 3,
    originalPrice: 21310,
  },
  {
    id: 2,
    title: "Tshirts",
    image: ["/images/pic12.png", "/images/pic12.png"],
    slug: "black t shirt",
    price: 150,
    discount: 50,
    category: "Tshirts",
    discrption:
      "A versatile black shirt perfect for any casual or formal occasion.",
    size: ["s", "m", "l ", "xl"],
    color: ["#fffff", "#000000", "#e60000"],
    qty: 1,
    rating: 3,
    originalPrice: 210,
  },
  {
    id: 2,
    title: "Tshirts",
    image: ["/images/pic11.png", "/images/pic12.png"],
    slug: "black t shirt",
    price: 150,
    discount: 50,
    category: "Tshirts",
    discrption:
      "A versatile black shirt perfect for any casual or formal occasion.",
    size: ["s", "m", "l ", "xl"],
    color: ["#fffff", "#000000", "#e60000"],
    qty: 1,
    rating: 4,
    originalPrice: 2000,
  },
  // Pants
  {
    id: 3,
    title: "black pants",
    image: ["/images/pic7.png", "/images/pic5.png"],
    slug: " Pants",
    price: 150,
    discount: 10,
    category: "Pants",
    discrption:
      "A versatile black shirt perfect for any casual or formal occasion.",
    size: ["s", "m", "l ", "xl"],
    color: ["#fffff", "#000000", "#e60000"],
    qty: 1,
    rating: 4,
    originalPrice: 1110,
  },
  {
    id: 3,
    title: "black pants",
    image: ["/images/pic8.png", "/images/pic5.png"],
    slug: " Pants",
    price: 150,
    discount: 40,
    category: "Pants",
    discrption:
      "A versatile black shirt perfect for any casual or formal occasion.",
    size: ["s", "m", "l ", "xl"],
    color: ["#fffff", "#000000", "#e60000"],
    qty: 1,
    rating: 3,
    originalPrice: 2000,
  },
  {
    id: 3,
    title: "black pants",
    image: ["/images/pic7.png", "/images/pic5.png"],
    slug: " Pants",
    price: 150,
    discount: 60,
    category: "Pants",
    discrption:
      "A versatile black shirt perfect for any casual or formal occasion.",
    size: ["s", "m", "l ", "xl"],
    color: ["#fffff", "#000000", "#e60000"],
    qty: 1,
    rating: 3,
    originalPrice: 2220,
  },
  {
    id: 3,
    title: "black pants",
    image: ["/images/pic8.png", "/images/pic5.png"],
    slug: " Pants",
    price: 150,
    discount: 20,
    category: "Pants",
    discrption:
      "A versatile black shirt perfect for any casual or formal occasion.",
    size: ["s", "m", "l ", "xl"],
    color: ["#fffff", "#000000", "#e60000"],
    qty: 1,
    rating: 3,
    originalPrice: 1000,
  },
  // Brands
  {
    id: 4,
    title: "yellow",
    image: ["/images/pic4.png", "/images/pic9.png"],
    slug: "Brands",
    price: 150,
    discount: 30,
    category: "Brands",
    discrption:
      "A versatile black shirt perfect for any casual or formal occasion.",
    size: ["s", "m", "l ", "xl"],
    color: ["#fffff", "#000000", "#e60000"],
    qty: 1,
    rating: 4,
    originalPrice: 2320,
  },
  {
    id: 4,
    title: "yellow",
    image: ["/images/pic5.png", "/images/pic9.png"],
    slug: "Brands",
    price: 150,
    discount: 30,
    category: "Brands",
    discrption:
      "A versatile black shirt perfect for any casual or formal occasion.",
    size: ["s", "m", "l ", "xl"],
    color: ["#fffff", "#000000", "#e60000"],
    qty: 1,
    rating: 2,
    originalPrice: 10108,
  },
];
